name: 'PlayerLocate'
version: '1.0.0'
main: org.playerlocate.playerlocate.PlayerLocate
api-version: 1.13
commands:
    locateplayer:
      description: "Lock your chests"
      usage: "§cUsage: /<command> playername"
      permission: PlayerLocate.locate
